// Ejemplos de datos para poblar Firestore en fase de desarrollo

const FIREBASE_EXAMPLE_DATA = {
  users: {
    user_id_1: {
      id: 'user_id_1',
      email: 'maria@example.com',
      name: 'María López',
      zone: 'Condesa',
      createdAt: 1700000000,
      photoUrl: 'https://via.placeholder.com/150',
    },
    user_id_2: {
      id: 'user_id_2',
      email: 'juan@example.com',
      name: 'Juan García',
      zone: 'Polanco',
      createdAt: 1700100000,
      photoUrl: 'https://via.placeholder.com/150',
    },
  },
  dogs: {
    dog_id_1: {
      id: 'dog_id_1',
      ownerId: 'user_id_1',
      name: 'Max',
      breed: 'Labrador',
      photoUrl: 'https://via.placeholder.com/300',
      ageCategory: 'adulto',
      gender: 'macho',
      size: 'grande',
      energyLevel: 'alto',
      personality: ['juguetón', 'amistoso', 'enérgico'],
      compatibility: ['pequeño', 'mediano'],
      zone: 'Condesa',
      createdAt: 1700000000,
      isLost: false,
    },
    dog_id_2: {
      id: 'dog_id_2',
      ownerId: 'user_id_1',
      name: 'Luna',
      breed: 'Golden Retriever',
      photoUrl: 'https://via.placeholder.com/300',
      ageCategory: 'adulto',
      gender: 'hembra',
      size: 'grande',
      energyLevel: 'medio',
      personality: ['tranquilo', 'amistoso', 'calmado'],
      compatibility: ['pequeño', 'mediano', 'grande'],
      zone: 'Condesa',
      createdAt: 1700010000,
      isLost: false,
    },
    dog_id_3: {
      id: 'dog_id_3',
      ownerId: 'user_id_2',
      name: 'Rocky',
      breed: 'Bulldog Francés',
      photoUrl: 'https://via.placeholder.com/300',
      ageCategory: 'cachorro',
      gender: 'macho',
      size: 'pequeño',
      energyLevel: 'alto',
      personality: ['juguetón', 'social', 'travieso'],
      compatibility: ['pequeño', 'mediano'],
      zone: 'Polanco',
      createdAt: 1700050000,
      isLost: false,
    },
  },
  matches: {
    match_id_1: {
      id: 'match_id_1',
      userId1: 'user_id_1',
      userId2: 'user_id_2',
      dogId1: 'dog_id_1',
      dogId2: 'dog_id_3',
      status: 'pending',
      createdAt: 1700200000,
    },
    match_id_2: {
      id: 'match_id_2',
      userId1: 'user_id_1',
      userId2: 'user_id_2',
      dogId1: 'dog_id_2',
      dogId2: 'dog_id_3',
      status: 'accepted',
      createdAt: 1700210000,
      respondedAt: 1700220000,
    },
  },
  lost_dogs: {
    lost_dog_id_1: {
      id: 'lost_dog_id_1',
      ownerId: 'user_id_1',
      dogId: 'dog_id_1',
      dogName: 'Buddy',
      description: 'Perro blanco con manchas marronnes, collar rojo. Muy amigable.',
      location: 'Parque España, Condesa',
      date: 1700300000,
      resolved: false,
      photoUrl: 'https://via.placeholder.com/300',
    },
  },
};

module.exports = FIREBASE_EXAMPLE_DATA;
